---
# - name: Incial playbook macos
# - name: Install, configure and start brew
#   block:
#     - name: Ensuring Homebrew Is Installed
#       ansible.builtin.stat:
#         path: /usr/homebrew/bin/brew
#       register: homebrew_check
#
#     - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
#       ansible.builtin.fail:
#         msg: Homebrew is missing...Install from http://brew.sh/
#       when:
#         - not homebrew_check.stat.exists
#         - not install_homebrew_if_missing
#
#     - name: Installing Homebrew
#       ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#       when:
#         - not homebrew_check.stat.exists
#         - install_homebrew_if_missing
#
#     - name: Updating Homebrew
#       community.general.homebrew:
#         update_homebrew: true
#       when: homebrew_check.stat.exists
#
#     - name: Upgrading Homebrew Packages
#       community.general.homebrew:
#         upgrade_all: "{{ upgrade_homebrew_packages }}"
#       register: result
#       until: result is successful
#       when: homebrew_check.stat.exists
#
#     - name: Installing Homebrew Cask Packages
#       homebrew_cask:
#         name: "{{ brew_cask_packages }}"
#         state: present
#       register: result
#       until: result is successful
#       when: homebrew_check.stat.exists
#
#     - name: Installing Homebrew Packages
#       community.general.homebrew:
#         name: "{{ brew_packages }}"
#         state: present
#       register: result
#       until: result is successful
#       when: homebrew_check.stat.exists
