---
- name: Verificar o sistema operacional e chamar o playbook correto
  hosts: all
  gather_facts: true
  become: true
  vars:
    venv_path: /opt/venv

  tasks:
    - name: Incluir homebrew tasks para macOS
      ansible.builtin.include_tasks: roles/brew_macOS.yaml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Incluir zsh tasks para macOS
      ansible.builtin.include_tasks: roles/zsh_macOS.yaml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Incluir tarefas para Linux se o sistema for Linux
      ansible.builtin.include_tasks: roles/linux/tasks/main.yaml
      when: ansible_facts['os_family'] == 'Debian'

    - name: Mensagem para sistema operacional não suportado
      ansible.builtin.debug:
        msg: "Sistema operacional não suportado"
      when: ansible_facts['os_family'] not in ['Darwin', 'Debian']

    - name: Ansible facts OS family
      ansible.builtin.debug:
        msg: "{{ ansible_os_family }}"
