---
# TODO: linux config
# TODO: install packages
- name: Update apt
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600

- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
    vars:
      packages:
        - wget
        - neovim
        - git
        - stow
        - tmux
        - zsh
        - bat
# TODO: zsh config
# TODO: oh my zsh config
# TODO: clone dotfiles repository
# TODO: tmux config
# TODO: install font
# TODO: stow config
